[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project]
name = "pilot"
version = "1.0.0"
description = "Federated Learning for Banking"
license = "Apache-2.0"
dependencies = [ "flwr[simulation]>=1.24.0", "torch>=2.7.1", "pandas", "scikit-learn", "numpy",]

[tool.flwr.app]
publisher = "fabiankargl"

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.app.components]
serverapp = "pilot.server_app:app"
clientapp = "pilot.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 10
fraction-train = 1.0
fraction-evaluate = 1.0
local-epochs = 3
lr = 0.005
min-available-clients = 3
strategy = "fedprox"
proximal-mu = 0.1
model-type = "nn"

[tool.flwr.federations.remote-federation]
address = "<SUPERLINK-ADDRESS>:<PORT>"
insecure = true

[tool.flwr.federations.local-simulation.options]
num-supernodes = 3

[tool.hatch.build.targets.wheel]
packages = [ ".",]

[tool.flwr.federations.local-simulation.options.backend.client-resources]
num-cpus = 4
num-gpus = 0.0
